coverage_service: cobertura_xml
xcodeproj: SwiftAA.xcodeproj
scheme: "SwiftAA-iOS"
source_directory:
  - SwiftAA/Swift
output_directory: 
  - TestReports
ignore:
  - SwiftAA/Obj-C
  - AAPlusTests/*
  - SwiftAATests/*
  - SwiftAATests-iOS/*
  - TestReports/*
  - libswiftaa/*
  - aaplus*
