coverage_service: cobertura_xml
xcodeproj: SwiftAA.xcodeproj
scheme: "SwiftAA-iOS"
source_directory:
  - SwiftAA
output_directory:
  - TestReports
ignore:
  - Sources/ObjCAA/*
  - Sources/aaplus*
  - Tests/AAPlusTests/*
  - Tests/SwiftAATests/*
  - Tests/SwiftAATests-iOS/*
  - TestReports/*
