language: swift
xcode_project: SwiftAA.xcodeproj
xcode_scheme: SwiftAA-iOS
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2
cache: bundler
before_install: 
  - rvm use $RVM_RUBY_VERSION
install: 
  - bundle install --without=documentation 
script:
  - xcodebuild clean build test -project SwiftAA.xcodeproj -scheme SwiftAA-iOS -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,OS=10.2,name=iPhone 7' ONLY_ACTIVE_ARCH=NO
after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash) -f TestReports/cobertura.xml -X coveragepy -X gcov -X xcode

